export enum AcademicRank {
  INTERN = 'INTERN',

  ASSISTANT = 'ASSISTANT',

  HEAD_TEACHER = 'HEAD_TEACHER',

  DOTSENT = 'DOTSENT',

  PROFESSOR = 'PROFESSOR',

  HEAD_DEPARTMENT = 'HEAD_DEPARTMENT',
}
